pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - author=Mic92
    actions:
      merge:
        method: merge
      delete_head_branch: {}
