name: Create release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # matches releases
      - '[0-9].[0-9].[0-9]'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release notes
        id: release-notes
        run: ./bin/print-release-notes.sh
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "${{ steps.release-notes.outputs.release_name }}"
          body: "${{ steps.release-notes.outputs.body }}"
          prerelease: false
